version: '2'

services:
 web:
  container_name: drupal
  image: drupal:latest
  ports:
   - "9081:80"
  volumes:
   - ./code:/code
  links:
   - drupaldb
 drupaldb:
  container_name: drupaldb
  image: mysql:latest
  env_file:
   - ./common.env
  volumes:
   - ./db:/var/lib/mysql
 phpmyadmin:
  container_name: drupalphpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
   - "9082:80"
  links:
   - drupaldb
