image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker info

build-docker:
    stage: build
    except:
        refs:
            - master
    script:
     - docker build -t docker-compose docker-compose
     - docker tag docker-compose udienz/docker-compose:latest
