image: docker:latest

services:
 - docker:dind

stages:
 - build
 - deploy

build-docker:
    stage: build
    except:
        refs:
            - master
    script:
     - docker build -t docker-compose docker-compose
     - docker tag docker-compose udienz/docker-compose:latest
     - docker login -u="$DOCKERUSER" -p="$DOCKERPASS"
     - docker push udienz/docker-compose:latest

build-drupal:
    image: udienz/docker-compose
    stage: build
    except:
        refs:
            - master
    script:
        - cd drupal
        - bash gen-env.sh
        - docker-compose -f docker-compose.yml config

build-nginx-php-mariadb:
    image: udienz/docker-compose
    stage: build
    except:
        refs:
            - master
    script:
        - cd nginx-php-mariadb
        - docker-compose -f docker-compose.yml config

build-wordpress-apache:
    image: udienz/docker-compose
    stage: build
    except:
        refs:
            - master
    script:
        - cd wordpress
        - bash gen-env.sh
        - docker-compose -f apache.yml config

build-wordpress-fpm:
    image: udienz/docker-compose
    stage: build
    except:
        refs:
            - master
    script:
        - cd wordpress
        - bash gen-env.sh
        - docker-compose -f fpm.yml config

create-pr:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - $CI_PROJECT_DIR/utils/merge.sh
    when: on_success

publish-success:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - $CI_PROJECT_DIR/utils/push-to-github.sh success
    when: on_success

publish-fail:
    image: udienz/gitlab-merge-resource
    before_script: []
    stage: deploy
    except:
        refs:
            - master
    script:
        - $CI_PROJECT_DIR/utils/push-to-github.sh failure
    when: on_failure
