version: '2'
services:
 wordpress:
  image: wordpress
  container_name: wordpress
  links:
   - wordpress_db:mysql
  volumes:
   - ./code:/code
  ports:
   - 127.0.0.1:8081:80
 wordpress_db:
  image: mariadb
  container_name: wordpress_db
  env_file:
   - ./common.env
  volumes:
   - ./db:/var/lib/mysql
