version: '2'
services:
 wordpress:
  image: wordpress:fpm
  container_name: wordpress
  env_file:
   - ./common.env
  links:
   - wordpress_db:mysql
  volumes:
   - ./code:/code
  ports:
   - "80:80"
 wordpress_db:
  image: mariadb
  container_name: wordpress_db
  env_file:
   - ./common.env
  volumes:
   - ./db:/var/lib/mysql
